version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.0.0
executors:
  docker-executor:
    docker:
      - image: public.ecr.aws/p5h0u5q6/node-sonar:21.1.0
    resource_class: medium
parameters:
  repo:
    type: string
    default: "${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-build"
  tag:
    type: string
    default: '"<< pipeline.number >>"'

jobs:
  build:
    executor: docker-executor
    steps:
      - run: apt-get -y update; apt-get -y install curl unzip
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
            - deps-
      - run: npm i
      - save_cache:
          key: deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      #      - code-analysis
      - run: npm run build
      - run: npm ci --production
      - setup_remote_docker:
          version: default
      - aws-ecr/build-and-push-image:
          repo: << pipeline.parameters.repo >>
          tag: << pipeline.parameters.tag >>
          create-repo: true
          checkout: false
workflows:
  build-and-deploy:
    jobs:
      - build:
          context:
            - ecr-<< pipeline.git.branch >>
            - << pipeline.git.branch >>
            - aws
          filters:
            branches:
              only:
                - main
                - staging
                - dev
      - aws-ecs/deploy-service-update:
          name: deploy
          cluster-name: $ECS_CLUSTER
          service-name: '${CIRCLE_PROJECT_REPONAME}'
          container-image-name-updates: 'container=${CIRCLE_PROJECT_REPONAME},image-and-tag=${AWS_ECR_ACCOUNT_URL}/<< pipeline.parameters.repo >>:<< pipeline.parameters.tag >>'
          family: $CIRCLE_PROJECT_REPONAME
          context:
            - common
            - ecr-<< pipeline.git.branch >>
            - << pipeline.git.branch >>
            - aws
          filters:
            branches:
              only:
                - main
                - dev
          requires:
            - build